#!/usr/bin/env bash

dev_commit() {
pushd ~/pandoras-box
git add .
git commit -m "automated dev commit"
git push origin main
popd

pushd ~/dotfiles
git add .
git commit -m "Automated dev commit"
git push origin main
popd

pushd ~/Games/planet-game
git add .
git commit -m "Automated dev commit"
git push origin main
popd
}

dev_commit > /dev/null
echo("==============================BANG============================")
